sudo: false
language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "9"
  - "10"
install:
  - yarn
  - yarn global add codecov
script:
  - jest --coverage && codecov
after_success:
  - yarn run travis-deploy-once "yarn run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
